---
# tasks file for nonag

- name: Update Javascript to not display nag prompt
  ansible.builtin.replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: '\sExt.Msg.show\({'
    before: 'title: gettext\(.No valid subscription.\)'
    replace: ' void({ //Ext.Msg.show({'
  notify: restart pveproxy
